# Generated by Django 2.2.12 on 2020-04-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_user', models.TextField()),
                ('blog_text', models.TextField()),
                ('blog_date', models.TextField()),
            ],
        ),
    ]
