# Generated by Django 2.2.12 on 2020-04-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200401_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_date',
            field=models.DateTimeField(),
        ),
    ]
