# Generated by Django 2.2.12 on 2020-04-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200402_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_title',
            field=models.CharField(default='Temporary Title', max_length=120),
        ),
    ]
